services:
  diary-api:
    build: .
    container_name: diary-api
    ports:
      - 8888:8080
    environment:
      DB_HOST: diary-metadata
      DB_PORT: 5432
      DB_PASSWORD: example
  diary-metadata:
    image: postgres
    ports:
      - 6432:5432
    container_name: diary-metadata
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: diaries
    volumes:
      - diary-metadata-vol:/var/lib/postgresql/data
volumes:
  diary-metadata-vol:
  diary-contents-vol: