appPort: 8080
appEnv: development
swagger:
  validate: true
  specPath: ./api/swagger.yml
auth:
  jwtKey: "12345"
postgres:
  host: "localhost"
  port: 6432
  dbName: "diaries"
  user: "postgres"
  password: "example"
  sslMode: "disable"